# Generated by Django 4.2 on 2023-05-10 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=19, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be in the format "xxxx-xxxx-xxxx-xxxx" where x is a number', regex='^\\d{4}\\-\\d{4}\\-\\d{4}\\-\\d{4}$')])),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='CVV number must be either 3 or 4 digits.', regex='^\\d{3,4}$')])),
                ('expiry_date', models.CharField(max_length=16)),
                ('name_on_card', models.CharField(max_length=26)),
                ('last_4_digits', models.CharField(blank=True, editable=False, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemDetails', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='testUser',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Service.card')),
                ('full_name', models.CharField(max_length=36)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=26)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_4_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('service', models.CharField(default='PayPal', editable=False, max_length=6)),
                ('status', models.CharField(default='Outstanding', max_length=16)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Service.order')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.testuser')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.testuser'),
        ),
    ]
