# Generated by Django 4.2 on 2023-04-29 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(db_index=True, max_length=19, primary_key=True, serialize=False, unique=True)),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)])),
                ('expiry_date', models.DateField()),
                ('name_on_card', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Service.card')),
                ('full_name', models.CharField(max_length=36)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=26)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_4_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('service', models.CharField(default='PayPal', editable=False, max_length=6)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.card')),
            ],
        ),
    ]
