# Generated by Django 4.2 on 2023-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
