# Generated by Django 4.2 on 2023-04-29 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_card_last_4_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=19, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be in the format "xxxx xxxx xxxx xxxx".', regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_4_digits',
            field=models.CharField(blank=True, editable=False, max_length=4, null=True),
        ),
    ]
