# Generated by Django 4.2 on 2023-04-29 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=19, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be in the format "xxxx xxxx xxxx xxxx".', regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
