# Generated by Django 4.2 on 2023-04-29 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='CVV number must be either 3 or 4 digits.', regex='^\\d{3,4}$')]),
        ),
    ]
