# Generated by Django 4.2 on 2023-05-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_alter_card_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=30)),
                ('itemCode', models.CharField(max_length=26)),
                ('itemPrice', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='testUser',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Outstanding', max_length=16),
        ),
        migrations.AddField(
            model_name='card',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.testuser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.testuser'),
        ),
    ]
