# Generated by Django 4.2 on 2023-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_testorder_testuser_transaction_status_card_user_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='userId',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
