# Generated by Django 4.2 on 2023-05-08 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_alter_card_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=19, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be in the format "xxxx-xxxx-xxxx-xxxx" where x is a number', regex='^\\d{4}\\-\\d{4}\\-\\d{4}\\-\\d{4}$')]),
        ),
    ]
